SET SQLBLANKLINES ON
CREATE TABLE OG_ACTION 
(
  ACTION_ID NUMBER NOT NULL 
, ACTION VARCHAR2(20 BYTE) 
, CONSTRAINT OG_ACTION_PK PRIMARY KEY 
  (
    ACTION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_ACTION_PK ON OG_ACTION (ACTION_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_CATEGORY 
(
  CATEGORY_ID NUMBER NOT NULL 
, CATEGORY VARCHAR2(20 BYTE) 
, CONSTRAINT OG_CATEGORY_PK PRIMARY KEY 
  (
    CATEGORY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_CATEGORY_PK ON OG_CATEGORY (CATEGORY_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_CATEGORY_REFEREE 
(
  CATEGORY_REFEREE_ID NUMBER NOT NULL 
, CATEGORY_REFEREE VARCHAR2(20 BYTE) 
, CONSTRAINT OG_CATEGORY_REFEREE_PK PRIMARY KEY 
  (
    CATEGORY_REFEREE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_CATEGORY_REFEREE_PK ON OG_CATEGORY_REFEREE (CATEGORY_REFEREE_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_COLOUR 
(
  COLOUR_ID NUMBER NOT NULL 
, COLOUR VARCHAR2(20 BYTE) 
, CONSTRAINT OG_COLOUR_PK PRIMARY KEY 
  (
    COLOUR_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_COLOUR_PK ON OG_COLOUR (COLOUR_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_GENDER 
(
  GENDER_ID NUMBER(2, 0) NOT NULL 
, GENDER VARCHAR2(20 BYTE) 
, CONSTRAINT OG_GENDER_PK PRIMARY KEY 
  (
    GENDER_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_GENDER_PK ON OG_GENDER (GENDER_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_GROUP 
(
  GROUP_ID NUMBER(10, 0) NOT NULL 
, GROUPNAME VARCHAR2(20 BYTE) 
, ID_TEAM_1 NUMBER 
, ID_TEAM_2 NUMBER 
, ID_TEAM_3 NUMBER 
, ID_TEAM_4 NUMBER 
, CONSTRAINT OG_GROUP_PK PRIMARY KEY 
  (
    GROUP_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_GROUP_PK ON OG_GROUP (GROUP_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_MATCH 
(
  MATCH_ID NUMBER(10, 0) NOT NULL 
, STARTDATE DATE 
, ENDDATE DATE 
, STADIUM NUMBER NOT NULL 
, STATUS NUMBER NOT NULL 
, PHASE NUMBER NOT NULL 
, TEAM_1 NUMBER NOT NULL 
, TEAM_2 NUMBER NOT NULL 
, WINNER VARCHAR2(20 BYTE) 
, REFEREE NUMBER 
, MEDAL NUMBER NOT NULL 
, CONSTRAINT OG_MATCH_PK PRIMARY KEY 
  (
    MATCH_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_MATCH_PK ON OG_MATCH (MATCH_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_MEDAL 
(
  MEDAL_ID NUMBER(10, 0) NOT NULL 
, MEDAL VARCHAR2(20 BYTE) 
, CONSTRAINT OG_MEDAL_PK PRIMARY KEY 
  (
    MEDAL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_MEDAL_PK ON OG_MEDAL (MEDAL_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_MEDAL_STANDING 
(
  MEDAL_STANDING_ID NUMBER NOT NULL 
, ID_NATIONALITY NUMBER NOT NULL 
, GOLD NUMBER 
, SILVER NUMBER 
, BRONZE NUMBER 
, CONSTRAINT OG_MEDAL_STANDING_PK PRIMARY KEY 
  (
    MEDAL_STANDING_ID 
  , ID_NATIONALITY 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_MEDAL_STANDING_PK ON OG_MEDAL_STANDING (MEDAL_STANDING_ID ASC, ID_NATIONALITY ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_NATIONALITY 
(
  NATIONALITY_ID NUMBER(10, 0) NOT NULL 
, NATIONALITY VARCHAR2(20 BYTE) 
, CONSTRAINT OG_NATIONALITY_PK PRIMARY KEY 
  (
    NATIONALITY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_NATIONALITY_PK ON OG_NATIONALITY (NATIONALITY_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_NEW 
(
  NEW_ID NUMBER NOT NULL 
, TITLE VARCHAR2(80 BYTE) NOT NULL 
, HEADER VARCHAR2(150 BYTE) 
, CONTENT VARCHAR2(500 BYTE) 
, DATE_HOUR DATE NOT NULL 
, IMG VARCHAR2(100 BYTE) 
, CONSTRAINT OG_NEW_PK PRIMARY KEY 
  (
    NEW_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_NEW_PK ON OG_NEW (NEW_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_NEW_NOC 
(
  NEW NUMBER NOT NULL 
, NOC NUMBER NOT NULL 
, CONSTRAINT OG_NEW_NOC_PK1 PRIMARY KEY 
  (
    NEW 
  , NOC 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_NEW_NOC_PK1 ON OG_NEW_NOC (NEW ASC, NOC ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_NOC 
(
  NOC_ID NUMBER(10, 0) NOT NULL 
, NOC VARCHAR2(20 BYTE) 
, CONSTRAINT OG_NOC_PK PRIMARY KEY 
  (
    NOC_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_NOC_PK ON OG_NOC (NOC_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_PARTICIPANT 
(
  PARTICIPANT_ID NUMBER(10, 0) NOT NULL 
, WEIGHT NUMBER(3, 0) 
, HEIGHT NUMBER(3, 0) 
, ROLE NUMBER NOT NULL 
, PERSON NUMBER NOT NULL 
, CONSTRAINT OG_PARTICIPANT_PK PRIMARY KEY 
  (
    PARTICIPANT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_PARTICIPANT_PK ON OG_PARTICIPANT (PARTICIPANT_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_PERSON 
(
  PERSONA_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(35 BYTE) 
, SURNAME VARCHAR2(35 BYTE) 
, BIRTHDATE DATE 
, GENDER NUMBER NOT NULL 
, NOC NUMBER NOT NULL 
, NATIONALITY NUMBER NOT NULL 
, CONSTRAINT PERSONA_PK PRIMARY KEY 
  (
    PERSONA_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PERSONA_PK ON OG_PERSON (PERSONA_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_PHASE 
(
  PHASE_ID NUMBER(10, 0) NOT NULL 
, PHASE VARCHAR2(20 BYTE) 
, CONSTRAINT OG_PHASE_PK PRIMARY KEY 
  (
    PHASE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_PHASE_PK ON OG_PHASE (PHASE_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_REFEREE 
(
  REFEREE_ID NUMBER(10, 0) NOT NULL 
, CATEGORY NUMBER NOT NULL 
, PERSON NUMBER NOT NULL 
, CONSTRAINT OG_REFEREE_PK PRIMARY KEY 
  (
    REFEREE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_REFEREE_PK ON OG_REFEREE (REFEREE_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_RESULT 
(
  RESULT_ID NUMBER NOT NULL 
, HOME_TEAM NUMBER NOT NULL 
, AWAY_TEAM NUMBER NOT NULL 
, RES_1_HOME NUMBER 
, RES_1_AWAY NUMBER 
, RES_2_HOME NUMBER 
, RES_2_AWAY NUMBER 
, RES_ET1_HOME NUMBER 
, RES_ET1_AWAY NUMBER 
, RES_ET2_HOME NUMBER 
, RES_ET2_AWAY NUMBER 
, RES_TOTAL_HOME NUMBER 
, RES_TOTAL_AWAY NUMBER 
, RES_PEN_HOME NUMBER 
, RES_PEN_AWAY NUMBER 
, MATCH NUMBER NOT NULL 
, CONSTRAINT OG_RESULT_PK PRIMARY KEY 
  (
    RESULT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_RESULT_PK ON OG_RESULT (RESULT_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_ROLE 
(
  ROLE_ID NUMBER NOT NULL 
, ROLE VARCHAR2(20 BYTE) 
, CONSTRAINT ROLE_PK PRIMARY KEY 
  (
    ROLE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX ROLE_PK ON OG_ROLE (ROLE_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_STADIUM 
(
  STADIUM_ID NUMBER(10, 0) NOT NULL 
, NAME VARCHAR2(35 BYTE) 
, CAPACITY VARCHAR2(20 BYTE) 
, CONSTRAINT OG_STADIUM_PK PRIMARY KEY 
  (
    STADIUM_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_STADIUM_PK ON OG_STADIUM (STADIUM_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_STATISTIC_PARTICIPANT 
(
  STATISTIC_PARTICIPANT_ID NUMBER NOT NULL 
, PARTIC NUMBER NOT NULL 
, PJ NUMBER 
, TIT NUMBER 
, MJUG NUMBER 
, G VARCHAR2(20 BYTE) 
, ASIST VARCHAR2(20 BYTE) 
, FC VARCHAR2(20 BYTE) 
, FS VARCHAR2(20 BYTE) 
, CONSTRAINT OG_STATISTIC_PARTICIPANT_PK PRIMARY KEY 
  (
    STATISTIC_PARTICIPANT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_STATISTIC_PARTICIPANT_PK ON OG_STATISTIC_PARTICIPANT (STATISTIC_PARTICIPANT_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_STATISTIC_TEAM 
(
  STATISTIC_TEAM_ID NUMBER NOT NULL 
, TEAM NUMBER NOT NULL 
, NMATCH NUMBER 
, NMATCH_WINS NUMBER 
, NMATCH_EQ NUMBER 
, GF NUMBER 
, GC NUMBER 
, CONSTRAINT OG_STATISTIC_TEAM_PK PRIMARY KEY 
  (
    STATISTIC_TEAM_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_STATISTIC_TEAM_PK ON OG_STATISTIC_TEAM (STATISTIC_TEAM_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_STATUS 
(
  STATUS_ID NUMBER(10, 0) NOT NULL 
, STATUS VARCHAR2(20 BYTE) 
, CONSTRAINT OG_STATUS_PK PRIMARY KEY 
  (
    STATUS_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_STATUS_PK ON OG_STATUS (STATUS_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_STAT_MATCH_PARTIC 
(
  STAT_ID NUMBER NOT NULL 
, MATCH NUMBER NOT NULL 
, TEAM NUMBER NOT NULL 
, ACTION NUMBER NOT NULL 
, PARTIC NUMBER NOT NULL 
, MINUTE VARCHAR2(20 BYTE) 
, CONSTRAINT OG_MATCH_TEAM_PK PRIMARY KEY 
  (
    STAT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_MATCH_TEAM_PK ON OG_STAT_MATCH_PARTIC (STAT_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_TEAM 
(
  TEAM_ID NUMBER(10, 0) NOT NULL 
, NOC NUMBER NOT NULL 
, GENDER NUMBER NOT NULL 
, NATIONALITY NUMBER NOT NULL 
, HOME_COLOUR NUMBER NOT NULL 
, AWAY_COLOUR NUMBER NOT NULL 
, ID_GROUP NUMBER 
, CONSTRAINT OG_TEAM_PK PRIMARY KEY 
  (
    TEAM_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_TEAM_PK ON OG_TEAM (TEAM_ID ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_TEAM_ACTION 
(
  MATCH NUMBER 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE OG_TEAM_PARTIC 
(
  TEAM NUMBER NOT NULL 
, PARTIC NUMBER NOT NULL 
, DORSAL NUMBER NOT NULL 
, CONSTRAINT OG_TEAM_PARTIC_PK PRIMARY KEY 
  (
    TEAM 
  , PARTIC 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OG_TEAM_PARTIC_PK ON OG_TEAM_PARTIC (TEAM ASC, PARTIC ASC) 
      LOGGING 
      TABLESPACE "SYSAUX" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

CREATE UNIQUE INDEX OG_MATCH_UK1 ON OG_MATCH (MEDAL ASC) 
LOGGING 
TABLESPACE "SYSAUX" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_UK1 UNIQUE 
(
  ID_TEAM_1 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_GROUP_UK1 ON OG_GROUP (ID_TEAM_1 ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_UK2 UNIQUE 
(
  ID_TEAM_2 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_GROUP_UK2 ON OG_GROUP (ID_TEAM_2 ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_UK3 UNIQUE 
(
  ID_TEAM_3 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_GROUP_UK3 ON OG_GROUP (ID_TEAM_3 ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_UK4 UNIQUE 
(
  ID_TEAM_4 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_GROUP_UK4 ON OG_GROUP (ID_TEAM_4 ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_UK1 UNIQUE 
(
  MEDAL 
)
USING INDEX OG_MATCH_UK1
ENABLE;

ALTER TABLE OG_MEDAL_STANDING
ADD CONSTRAINT OG_MEDAL_UC_NATIONALITY UNIQUE 
(
  ID_NATIONALITY 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_MEDAL_UC_NATIONALITY ON OG_MEDAL_STANDING (ID_NATIONALITY ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_PARTICIPANT
ADD CONSTRAINT OG_PARTICIPANT_UK1 UNIQUE 
(
  PERSON 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_PARTICIPANT_UK1 ON OG_PARTICIPANT (PERSON ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_REFEREE
ADD CONSTRAINT OG_REFEREE_PERSON UNIQUE 
(
  PERSON 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_REFEREE_PERSON ON OG_REFEREE (PERSON ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_RESULT
ADD CONSTRAINT OG_RESULT_UK1 UNIQUE 
(
  MATCH 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_RESULT_UK1 ON OG_RESULT (MATCH ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_STATISTIC_PARTICIPANT
ADD CONSTRAINT OG_STATISTIC_PARTICIPANT_UK1 UNIQUE 
(
  PARTIC 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_STATISTIC_PARTICIPANT_UK1 ON OG_STATISTIC_PARTICIPANT (PARTIC ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_STATISTIC_TEAM
ADD CONSTRAINT OG_STATISTIC_TEAM_UK1 UNIQUE 
(
  TEAM 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_STATISTIC_TEAM_UK1 ON OG_STATISTIC_TEAM (TEAM ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_UK_NATIONALITY UNIQUE 
(
  NATIONALITY 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_TEAM_NATIONALITY ON OG_TEAM (NATIONALITY ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_TEAM_PARTIC
ADD CONSTRAINT OG_TEAM_PARTIC_UK1 UNIQUE 
(
  PARTIC 
)
USING INDEX 
(
    CREATE UNIQUE INDEX OG_TEAM_PARTIC_UK1 ON OG_TEAM_PARTIC (PARTIC ASC) 
    LOGGING 
    TABLESPACE "SYSAUX" 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      BUFFER_POOL DEFAULT 
    ) 
)
 ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_TEAM_1 FOREIGN KEY
(
  ID_TEAM_1 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_TEAM_2 FOREIGN KEY
(
  ID_TEAM_2 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_TEAM_3 FOREIGN KEY
(
  ID_TEAM_3 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_GROUP
ADD CONSTRAINT OG_GROUP_TEAM_4 FOREIGN KEY
(
  ID_TEAM_4 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_MEDAL FOREIGN KEY
(
  MEDAL 
)
REFERENCES OG_MEDAL
(
  MEDAL_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_PHASE FOREIGN KEY
(
  PHASE 
)
REFERENCES OG_PHASE
(
  PHASE_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_REFEREE FOREIGN KEY
(
  REFEREE 
)
REFERENCES OG_REFEREE
(
  REFEREE_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_STADIUM FOREIGN KEY
(
  STADIUM 
)
REFERENCES OG_STADIUM
(
  STADIUM_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_STATUS FOREIGN KEY
(
  STATUS 
)
REFERENCES OG_STATUS
(
  STATUS_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_TEAM_1 FOREIGN KEY
(
  TEAM_1 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ENABLE;

ALTER TABLE OG_MATCH
ADD CONSTRAINT OG_MATCH_TEAM_2 FOREIGN KEY
(
  TEAM_2 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ENABLE;

ALTER TABLE OG_MEDAL_STANDING
ADD CONSTRAINT OG_MEDAL_STANDING_NATIONALITY FOREIGN KEY
(
  ID_NATIONALITY 
)
REFERENCES OG_NATIONALITY
(
  NATIONALITY_ID 
)
ENABLE;

ALTER TABLE OG_NEW_NOC
ADD CONSTRAINT OG_NEW_NOC_NEW FOREIGN KEY
(
  NEW 
)
REFERENCES OG_NEW
(
  NEW_ID 
)
ENABLE;

ALTER TABLE OG_NEW_NOC
ADD CONSTRAINT OG_NEW_NOC_NOC FOREIGN KEY
(
  NOC 
)
REFERENCES OG_NOC
(
  NOC_ID 
)
ENABLE;

ALTER TABLE OG_PARTICIPANT
ADD CONSTRAINT OG_PARTICIPANT_PERSON FOREIGN KEY
(
  PERSON 
)
REFERENCES OG_PERSON
(
  PERSONA_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OG_PARTICIPANT
ADD CONSTRAINT OG_PARTICIPANT_ROLE FOREIGN KEY
(
  ROLE 
)
REFERENCES OG_ROLE
(
  ROLE_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_PERSON
ADD CONSTRAINT OG_PERSON_GENDER FOREIGN KEY
(
  GENDER 
)
REFERENCES OG_GENDER
(
  GENDER_ID 
)
ENABLE;

ALTER TABLE OG_PERSON
ADD CONSTRAINT OG_PERSON_NATIONALITY FOREIGN KEY
(
  NATIONALITY 
)
REFERENCES OG_NATIONALITY
(
  NATIONALITY_ID 
)
ENABLE;

ALTER TABLE OG_PERSON
ADD CONSTRAINT OG_PERSON_NOC FOREIGN KEY
(
  NOC 
)
REFERENCES OG_NOC
(
  NOC_ID 
)
ENABLE;

ALTER TABLE OG_REFEREE
ADD CONSTRAINT OG_REFEREE_CATEGORY_REFEREE FOREIGN KEY
(
  CATEGORY 
)
REFERENCES OG_CATEGORY_REFEREE
(
  CATEGORY_REFEREE_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_REFEREE
ADD CONSTRAINT OG_REFEREE_FK_PERSON FOREIGN KEY
(
  PERSON 
)
REFERENCES OG_PERSON
(
  PERSONA_ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE OG_RESULT
ADD CONSTRAINT OG_RESULT_MATCH FOREIGN KEY
(
  MATCH 
)
REFERENCES OG_MATCH
(
  MATCH_ID 
)
ENABLE;

ALTER TABLE OG_STATISTIC_PARTICIPANT
ADD CONSTRAINT OG_STATISTIC_PARTIC_PARTIC FOREIGN KEY
(
  PARTIC 
)
REFERENCES OG_PARTICIPANT
(
  PARTICIPANT_ID 
)
ENABLE;

ALTER TABLE OG_STATISTIC_TEAM
ADD CONSTRAINT OG_STATISTIC_TEAM_TEAM FOREIGN KEY
(
  TEAM 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ENABLE;

ALTER TABLE OG_STAT_MATCH_PARTIC
ADD CONSTRAINT OG_MATCH_TEAM_ACTION FOREIGN KEY
(
  ACTION 
)
REFERENCES OG_ACTION
(
  ACTION_ID 
)
ENABLE;

ALTER TABLE OG_STAT_MATCH_PARTIC
ADD CONSTRAINT OG_MATCH_TEAM_MATCH FOREIGN KEY
(
  MATCH 
)
REFERENCES OG_MATCH
(
  MATCH_ID 
)
ENABLE;

ALTER TABLE OG_STAT_MATCH_PARTIC
ADD CONSTRAINT OG_MATCH_TEAM_PARTICIPANT FOREIGN KEY
(
  PARTIC 
)
REFERENCES OG_PARTICIPANT
(
  PARTICIPANT_ID 
)
ENABLE;

ALTER TABLE OG_STAT_MATCH_PARTIC
ADD CONSTRAINT OG_MATCH_TEAM_TEAM FOREIGN KEY
(
  TEAM 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_AWAY_COLOUR FOREIGN KEY
(
  AWAY_COLOUR 
)
REFERENCES OG_COLOUR
(
  COLOUR_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_GENDER FOREIGN KEY
(
  GENDER 
)
REFERENCES OG_GENDER
(
  GENDER_ID 
)
ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_HOME_COLOUR FOREIGN KEY
(
  HOME_COLOUR 
)
REFERENCES OG_COLOUR
(
  COLOUR_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_NATIONALITY FOREIGN KEY
(
  NATIONALITY 
)
REFERENCES OG_NATIONALITY
(
  NATIONALITY_ID 
)
ENABLE;

ALTER TABLE OG_TEAM
ADD CONSTRAINT OG_TEAM_NOC FOREIGN KEY
(
  TEAM_ID 
)
REFERENCES OG_NOC
(
  NOC_ID 
)
ENABLE;

ALTER TABLE OG_TEAM_PARTIC
ADD CONSTRAINT OG_TEAM_PARTIC_PARTIC FOREIGN KEY
(
  PARTIC 
)
REFERENCES OG_PARTICIPANT
(
  PARTICIPANT_ID 
)
ON DELETE SET NULL ENABLE;

ALTER TABLE OG_TEAM_PARTIC
ADD CONSTRAINT OG_TEAM_PARTIC_TEAM FOREIGN KEY
(
  TEAM 
)
REFERENCES OG_TEAM
(
  TEAM_ID 
)
ENABLE;

COMMENT ON COLUMN OG_CATEGORY.CATEGORY_ID IS 'Identifier of a category for a match belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_CATEGORY_REFEREE.CATEGORY_REFEREE_ID IS 'Identifier of a category belonging to any referee';

COMMENT ON COLUMN OG_GENDER.GENDER_ID IS 'Identifier of a gender belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_GENDER.GENDER IS 'M:MAN, W:WOMAN, T:TEAM';

COMMENT ON COLUMN OG_GROUP.GROUP_ID IS 'Identifier of a group belonging to any competition and scope -> In our scenario: Group of football - GRoup A,B,C and D.';

COMMENT ON COLUMN OG_MATCH.MATCH_ID IS 'Identifier of a match belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_MEDAL.MEDAL_ID IS 'Identifier of a medalfor a match belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_NATIONALITY.NATIONALITY_ID IS 'Identifier of a nationality belonging to any person or team in any scope -> In our scenario: Football';

COMMENT ON COLUMN OG_NOC.NOC_ID IS 'Identifier of a NOC belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_PARTICIPANT.PARTICIPANT_ID IS 'Identifier of a athleta belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_PARTICIPANT.ROLE IS 'Identifier the default position of each athleta: goalkeeper, defender, ...,or coach.';

COMMENT ON COLUMN OG_PERSON.PERSONA_ID IS 'Identifier of a person belonging to any competition and scope';

COMMENT ON COLUMN OG_PHASE.PHASE_ID IS 'Identifier of a phase for a match belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_REFEREE.REFEREE_ID IS 'Identifier of a referee belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_RESULT.RESULT_ID IS 'Identifier the result of a match belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_ROLE.ROLE_ID IS 'Identifier the default position of each athleta: goalkeeper, defender, ...,or coach.';

COMMENT ON COLUMN OG_STADIUM.STADIUM_ID IS 'Identifier of a stadium belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_STATUS.STATUS_ID IS 'Identifier of a status for a match belonging to any competition and scope -> In our scenario: Football. It could be: SCHEDULE, LIVE, UNOFFICIAL or OFFICIAL.';

COMMENT ON COLUMN OG_TEAM.TEAM_ID IS 'Identifier of a athleta belonging to any competition and scope -> In our scenario: Football';

COMMENT ON COLUMN OG_TEAM_PARTIC.DORSAL IS 'Number of dorsal for each partic in each team is unique:1..15';
